### PR TITLE
fix: nested lists roundtrip

### LINKED ISSUE #529: Lists and nested lists are not roundtripable
When nesting lists the text of a list is wrapped in an additional `<p>`.

See the test case in https://github.com/adobe/helix-html2md/compare/nested-lists-roundtrip

Examples:

```
<li><a href="#" title="Navigate to Text 1">Text 1</a></li>
```

becomes 
```
<li>
  <p><a href="#" title="Navigate to Text 1">Text 1</a></p>
</li>
```

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #529

### CODE REVIEW

**Comment by tripodsan** [comment]
@buuhuu I think we can safely collapse all lists, because AFAICS, all docx2md also only create collapsed lists.
(the only risk is, that we change the bahviour of other BYOM projects that expect the <p>)

**Comment by buuhuu** [comment]
> the only risk is, that we change the bahviour of other BYOM projects that expect the

That is right. For AEM-based authoring w/ UE we would know if anyone is facing this as we already have a mismatch of the markup produced by AEM and EDS via html2md (this is where we found it). Customers that have that issue either have clientside code that can deal with it or are not affected at all.

@mhaack do you know any BOYM project that uses/used nested lists?

**Review by buuhuu — APPROVED** [review]

**Comment by buuhuu** [comment]
@tripodsan I think we are good to merge this. Haven't found a crosswalk customer where we used nested lists. We better make that change now, then later.

**Comment by tripodsan** [comment]
@buuhuu we had to revert this change, because it broke experience-league. we will re-apply it later, when they updated the clienside code.

**Pull request merged**
