### PR TITLE
Support og:image and twitter:image in page metadata

### LINKED ISSUE #590: Support og:image and twitter:image in page metadata
In Crosswalk, we have a requirement to enable authors to define `og:image` and `twitter:image` independently of the `image` metadata. Currently, these tags are stripped from the generated md document:
https://github.com/adobe/helix-html2md/blob/main/src/html2md.js#L108-L115
https://github.com/adobe/helix-html2md/blob/main/src/html2md.js#L128-L135

These tags should be preserved and included in the final metadata.

I will provide a PR.

### PR DESCRIPTION
**Pull request by jckautzmann**
- if available in the html, keep og:image and twitter:image as page metadata of the markdown document

Fixes #590 

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by jckautzmann** [comment]
@tripodsan Could you please have a look at the PR? Thx.

**Review by tripodsan — APPROVED** [review]
LGTM, but let's also ask @mhaack

**Review by buuhuu — APPROVED** [review]
lgtm

**Comment by jckautzmann** [comment]
Thx all for reviewing this PR. @tripodsan Could you please merge it?

**Pull request merged**
